org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.configuration-cache=false

minecraft_version=1.21.1
neo_version=21.1.234
loader_version_range=[4,)
minecraft_version_range=[1.21.1,1.22)

mod_id=urbanforma
mod_name=UrbanForma
mod_license=MIT
mod_version=1.1016+mc1.21.1
mod_group_id=com.urbanforma
mod_authors=Dotkk
mod_description=A compatibility port of the original UrbanForma 1.20.1 content for Minecraft 1.21.1.
