# Mod Properties
mod_group_id=com.urbanforma
mod_id=urbanforma
mod_name=UrbanForma
mod_license=MIT
mod_version=1.05d
mod_authors=YourName
mod_description=A modern urban construction mod

# Minecraft版本
minecraft_version=1.18.2
minecraft_version_range=[1.18.2,1.19)

# Forge版本
forge_version=40.2.4
forge_version_range=[40,)
loader_version_range=[40,)